# Desafio 006

Você recebeu um relatório com o registro de visitas de campo de uma equipe. O relatório contém a data da visita (como texto) e o tempo de duração em minutos. Seu chefe precisa de uma análise temporal dessas visitas para planejar o próximo mês.

### Seu código inicial:

In [1]:
import pandas as pd

# Relatório bruto do sistema de visitas
dados_visitas = {
    'ID_Visita': [1001, 1002, 1003, 1004, 1005, 1006],
    'Data_Visita': ['2026-01-10', '2026-01-15', '2026-02-02', '2026-02-20', '2026-03-05', '2026-03-12'],
    'Duração_Minutos': [20, 45, 15, 80, 35, 120]
}

df = pd.DataFrame(dados_visitas)
display(df)

   ID_Visita Data_Visita  Duração_Minutos
0       1001  2026-01-10               20
1       1002  2026-01-15               45
2       1003  2026-02-02               15
3       1004  2026-02-20               80
4       1005  2026-03-05               35
5       1006  2026-03-12              120

### Suas tarefas:

1. **Conversão de Datas**: A coluna 'Data_Visita' veio originalmente como texto. Converta essa coluna para o formato real de data do Pandas (datetime).

In [2]:
df["Data_Visita"] = pd.to_datetime(df["Data_Visita"], format="%Y-%m-%d")
display(df['Data_Visita'])

0   2026-01-10
1   2026-01-15
2   2026-02-02
3   2026-02-20
4   2026-03-05
5   2026-03-12
Name: Data_Visita, dtype: datetime64[us]

2. **Extração de Períodos**: Crie duas novas colunas no seu DataFrame:

 - 'Ano': Extraia apenas o ano da data convertida.

 - 'Mes': Extraia apenas o número do mês da data convertida

In [3]:
df["Ano"] = df["Data_Visita"].dt.year
df["Mês"] = df["Data_Visita"].dt.month
display(df[['Ano', 'Mês']])

    Ano  Mês
0  2026    1
1  2026    1
2  2026    2
3  2026    2
4  2026    3
5  2026    3

3. **Função Personalizada**: Crie uma função normal em Python chamada classificar_duracao(minutos). Se a visita durou até 30 minutos, retorne 'Rápida'. Se durou entre 31 e 60 minutos, retorne 'Padrão'. Se durou mais de 60 minutos, retorne 'Longa'.
Aplique essa função no DataFrame criando uma nova coluna chamada 'Classificacao'.

In [4]:
def classificar_duracao(minutos):
    if minutos <= 30:
        return "Rápida"
    elif minutos <= 60:
        return "Padrão"
    else:
        return "Longa"

df["Classificação"] = df["Duração_Minutos"].apply(classificar_duracao)
display(df["Classificação"])

0    Rápida
1    Padrão
2    Rápida
3     Longa
4    Padrão
5     Longa
Name: Classificação, dtype: str

4. **Contagem por Categoria**: Descubra quantas visitas de cada 'Classificacao' (Rápida, Padrão, Longa) aconteceram no total.

In [6]:
display(df['Classificação'].value_counts())

Classificação
Rápida    2
Padrão    2
Longa     2
Name: count, dtype: int64