# Desafio 012

Vamos simular que você precisa conectar um script em Python a um banco corporativo estruturado em rede. Você criará um script modular que carrega as credenciais de forma segura e simula o fluxo correto de conexão que você usaria no banco de dados da sua empresa.

### Suas Tarefas:

1. Use o módulo nativo `os` do Python para simular a leitura de variáveis de ambiente.

In [4]:
import os
from dotenv import load_dotenv

load_dotenv()

db_host = os.environ.get("DB_HOST")
db_user = os.environ.get("DB_USER")
db_pass = os.environ.get("DB_PASS") or ""
db_data = os.environ.get("DB_NAME")

2. Crie uma função chamada `conectar_banco()` que simula o teste de conexão.

In [5]:
from sqlalchemy import create_engine

def conectar_banco(
    host,
    user,
    password,
    database
):
    url_conexao = f"mysql+mysqlconnector://{user}:{password}@{host}/{database}"
    engine = create_engine(url_conexao)
    return engine

3. Leia os dados da nossa tabela de visitas simulando uma consulta remota

In [10]:
import pandas as pd

os.system("mariadbd-safe &")

conexao = conectar_banco(
    db_host,
    db_user,
    db_pass,
    db_data
)

def ler_sql(cmd, cnx):
    try:
        resposta = pd.read_sql(
            cmd,
            cnx
        )
        return resposta
    except Exception as e:
        print(f"Erro: {e}")

atendimentos = ler_sql(
    "SELECT * FROM atendimentos",
    conexao
)
pacientes = ler_sql(
    "SELECT * FROM pacientes",
    conexao
)

tabela_inexistente = ler_sql(
    "SELECT * FROM tabela",
    conexao
)

display(atendimentos)
display(pacientes)

Erro: Execution failed on sql 'SELECT * FROM tabela': (mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'curso.tabela' doesn't exist
[SQL: SELECT * FROM tabela]
(Background on this error at: https://sqlalche.me/e/20/f405)

   ID_Atendimento  ID_Paciente       Agravo  Tempo_Minutos
0            1001            1       Dengue             25
1            1002            2        Gripe             15
2            1003            3       Dengue             30
3            1004            4        Gripe             20
4            1005            5  Hipertensão             45
5            1006            6  Hipertensão             40

   ID_Paciente         Nome  Idade
0            1       Carlos     24
1            2          Ana     28
2            3  Seu Antenor     88
3            4        Julia     26
4            5       Marcos     52
5            6          Eva     54