# Desafio 008

Imagine que o sistema de prontuários ou visitas da sua unidade de saúde salva tudo em um banco de dados MariaDB/MySQL/SQLite. O seu chefe quer que você puxe esses dados usando comandos SQL de dentro do Python, use o Pandas para fazer uma análise descritiva completa (.describe()) e filtre os resultados.

### Seu código inicial:

In [14]:
import pandas as pd
import sqlite3

conexao = sqlite3.connect(":memory:")
cursor = conexao.cursor()

cursor.execute("""
    CREATE TABLE visitas (
        id INTEGER PRIMARY KEY,
        Paciente TEXT,
        Idade INTEGER,
        Agravo TEXT,
        Tempo_Minutos INTEGER
    )
""")

dados = [
    (1, "Dona Maria", 65, "Hipertensão", 25),
    (2, "Seu José", 72, "Diabetes", 40),
    (3, "Ana Júlia", 12, "Asma", 15),
    (4, "Carlos Silva", 58, "Hipertensão", 20),
    (5, "Dona Francisca", 48, "Hipertensão", 30),
    (6, "Seu Antônio", 80, "Diabetes", 50)
]
cursor.executemany(
    "INSERT INTO visitas VALUES (?, ?, ?, ?, ?)",
    dados
)
conexao.commit()

### Suas tarefas:

1. **Criar a Conexão**: Crie a conexão com o banco de dados simulado e carregue a tabela inicial.
2. **O Grande SELECT**: Use o comando `pd.read_sql_query()` para executar um `SELECT * FROM visitas` e trazer os dados do banco direto para um DataFrame do Pandas.

In [15]:
df = pd.read_sql_query(
    "SELECT * FROM visitas",
    conexao
)
display(df)

   id        Paciente  Idade       Agravo  Tempo_Minutos
0   1      Dona Maria     65  Hipertensão             25
1   2        Seu José     72     Diabetes             40
2   3       Ana Júlia     12         Asma             15
3   4    Carlos Silva     58  Hipertensão             20
4   5  Dona Francisca     48  Hipertensão             30
5   6     Seu Antônio     80     Diabetes             50

3. **O Raio-X Estatístico**: Use o método `.describe()` do Pandas para exibir na tela o resumo estatístico das colunas numéricas (Idade e Tempo de Atendimento).

In [16]:
display(df.describe())

             id      Idade  Tempo_Minutos
count  6.000000   6.000000       6.000000
mean   3.500000  55.833333      30.000000
std    1.870829  24.152985      13.038405
min    1.000000  12.000000      15.000000
25%    2.250000  50.500000      21.250000
50%    3.500000  61.500000      27.500000
75%    4.750000  70.250000      37.500000
max    6.000000  80.000000      50.000000

4. **Filtro SQL Avançado**: Faça uma nova consulta ao banco trazendo apenas os registros onde a Idade seja maior que 50 anos E o Agravo seja igual a 'Hipertensão'. Exiba essa tabela final.

In [17]:
df2 = pd.read_sql_query(
    """
    SELECT * FROM visitas
    WHERE Idade > 50 AND Agravo = 'Hipertensão'
    """,
    conexao
)
display(df2)

   id      Paciente  Idade       Agravo  Tempo_Minutos
0   1    Dona Maria     65  Hipertensão             25
1   4  Carlos Silva     58  Hipertensão             20

In [18]:
conexao.close()