# Desafio 007

Você recebeu um relatório de registros de atendimentos de saúde comunitária. Porém, os nomes das doenças foram digitados de qualquer jeito pelos agentes, e o relatório final precisa cruzar os bairros com os meses de atendimento em formato de matriz para a gestão tomar decisões.

### Seu código inicial:

In [2]:
import pandas as pd

# Relatório bruto de atendimentos
dados_atendimentos = {
    'ID_Registro': [1, 2, 3, 4, 5, 6, 7, 8],
    'Bairro': ['Centro', 'Vila Nova', 'Centro', 'Vila Nova', 'Centro', 'Subúrbio', 'Vila Nova', 'Subúrbio'],
    'Mês': ['Janeiro', 'Janeiro', 'Janeiro', 'Fevereiro', 'Fevereiro', 'Fevereiro', 'Março', 'Março'],
    'Agravo/Doença': [' dengue ', 'DENGUE', ' Gripe', 'gripe', 'Dengue', 'Gripe ', ' Covid', 'COVID']
}

df = pd.DataFrame(dados_atendimentos)
display(df)

   ID_Registro     Bairro        Mês Agravo/Doença
0            1     Centro    Janeiro       dengue
1            2  Vila Nova    Janeiro        DENGUE
2            3     Centro    Janeiro         Gripe
3            4  Vila Nova  Fevereiro         gripe
4            5     Centro  Fevereiro        Dengue
5            6   Subúrbio  Fevereiro        Gripe
6            7  Vila Nova      Março         Covid
7            8   Subúrbio      Março         COVID

### Suas tarefas:

1. **Padronização de Texto** (Limpeza de Strings): Os nomes na coluna 'Agravo/Doença' vieram bagunçados (ex: " dengue ", "DENGUE", "Dengue"). Deixe todos os textos dessa coluna padronizados: sem espaços em branco nas pontas e com todas as letras em maiúsculo.

In [5]:
df["Agravo/Doença"] = df["Agravo/Doença"].apply(lambda x: x.title())
display(df["Agravo/Doença"])

0    Dengue
1    Dengue
2     Gripe
3     Gripe
4    Dengue
5     Gripe
6     Covid
7     Covid
Name: Agravo/Doença, dtype: str

2. **Criar a Tabela Dinâmica** (Pivot Table): Crie um novo DataFrame chamado matriz_atendimentos que cruze as informações da seguinte forma:
  
  - As Linhas devem ser os Bairros.

  - As Colunas devem ser os Meses.

  - Os Valores internos devem ser a Contagem de atendimentos que aconteceram naquele cruzamento.

In [7]:
matriz_atendimentos = df.pivot_table(
    index="Bairro",
    columns="Mês",
    values="Agravo/Doença",
    aggfunc="count",
    fill_value=0
)
display(matriz_atendimentos)

Mês        Fevereiro  Janeiro  Março
Bairro
Centro             1        2      0
Subúrbio           1        0      1
Vila Nova          1        1      1

3. **Totalizadores**: Adicione uma linha final chamada "TOTAL" na sua Tabela Dinâmica que mostre a soma de atendimentos de cada mês (soma das colunas).

> (Dica: `matriz_atendimentos.loc['TOTAL'] = matriz_atendimentos.sum()`).

In [8]:
matriz_atendimentos.loc["Total"] = matriz_atendimentos.sum()
display(matriz_atendimentos)

Mês        Fevereiro  Janeiro  Março
Bairro
Centro             1        2      0
Subúrbio           1        0      1
Vila Nova          1        1      1
Total              3        3      2